-- =============================================
-- NEWS SERVICE DATABASE - SAMPLE DATA
-- =============================================

-- Connect to newsdb
\c newsdb;

-- Insert sample news articles
INSERT INTO news(user_id, title, content, field_id, exam_id, news_type, status, created_at, published_at, expired_at, approved_by, useful_vote, interest_vote, company_name, location, salary, experience, position, working_hours, deadline, application_method) VALUES 
(1, 'ReactJS 18 New Features Released', 'ReactJS 18 introduces several exciting new features including concurrent rendering, automatic batching, and improved performance. These features make React applications faster and more efficient.', 1, NULL, 'NEWS', 'PUBLISHED', NOW() - INTERVAL '5 days', NOW() - INTERVAL '4 days', NULL, 1, 25, 18, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(2, 'Spring Boot 3.0 Major Updates', 'Spring Boot 3.0 brings significant improvements including native compilation support, enhanced observability, and better integration with Jakarta EE. This release focuses on performance and developer experience.', 1, NULL, 'NEWS', 'PUBLISHED', NOW() - INTERVAL '4 days', NOW() - INTERVAL '3 days', NULL, 1, 20, 15, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(1, 'Docker Best Practices for Production', 'Learn the essential Docker best practices for production deployments including security considerations, resource management, and monitoring strategies.', 4, NULL, 'NEWS', 'PUBLISHED', NOW() - INTERVAL '3 days', NOW() - INTERVAL '2 days', NULL, 1, 15, 12, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(2, 'Machine Learning Trends 2024', 'Explore the latest trends in machine learning including large language models, computer vision advances, and ethical AI considerations for 2024.', 5, NULL, 'NEWS', 'PUBLISHED', NOW() - INTERVAL '2 days', NOW() - INTERVAL '1 day', NULL, 1, 30, 25, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(1, 'API Gateway Design Patterns', 'Understanding different API Gateway design patterns and their implementation strategies for microservices architecture.', 1, NULL, 'NEWS', 'PENDING', NOW() - INTERVAL '1 day', NULL, NULL, NULL, 0, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(2, 'Database Sharding Strategies', 'Comprehensive guide to database sharding strategies for handling large-scale applications and improving performance.', 1, NULL, 'NEWS', 'APPROVED', NOW() - INTERVAL '12 hours', NULL, NULL, 1, 8, 5, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);

-- Insert sample recruitment posts
INSERT INTO news(user_id, title, content, field_id, exam_id, news_type, status, created_at, published_at, expired_at, approved_by, useful_vote, interest_vote, company_name, location, salary, experience, position, working_hours, deadline, application_method) VALUES 
(2, 'Senior ReactJS Developer - ABC Tech', 'We are looking for a Senior ReactJS Developer to join our growing team. You will be responsible for developing and maintaining our web applications using ReactJS, Redux, and modern frontend technologies.', 1, 1, 'RECRUITMENT', 'PUBLISHED', NOW() - INTERVAL '3 days', NOW() - INTERVAL '2 days', NOW() + INTERVAL '30 days', 1, 12, 35, 'ABC Tech', 'Ho Chi Minh City', '2000-3000 USD', '3-5 years', 'Senior ReactJS Developer', '9AM-6PM', '2024-12-31', 'Send CV to hr@abctech.com'),
(2, 'Java Spring Boot Developer - XYZ Corp', 'Join our backend development team as a Java Spring Boot Developer. You will work on building scalable microservices and RESTful APIs using Spring Boot, Spring Security, and related technologies.', 1, 2, 'RECRUITMENT', 'PUBLISHED', NOW() - INTERVAL '2 days', NOW() - INTERVAL '1 day', NOW() + INTERVAL '25 days', 1, 18, 28, 'XYZ Corp', 'Hanoi', '1800-2500 USD', '2-4 years', 'Java Spring Boot Developer', '8AM-5PM', '2024-12-25', 'Apply through our website: xyzcorp.com/careers'),
(2, 'Full Stack Developer - TechStart', 'We need a Full Stack Developer who can work on both frontend and backend technologies. Experience with ReactJS, Node.js, and cloud platforms is required.', 1, 3, 'RECRUITMENT', 'PUBLISHED', NOW() - INTERVAL '1 day', NOW() - INTERVAL '12 hours', NOW() + INTERVAL '20 days', 1, 15, 22, 'TechStart', 'Da Nang', '1500-2200 USD', '2-3 years', 'Full Stack Developer', 'Flexible', '2024-12-20', 'Email: jobs@techstart.vn'),
(2, 'DevOps Engineer - CloudTech', 'Looking for a DevOps Engineer to manage our cloud infrastructure and CI/CD pipelines. Experience with Docker, Kubernetes, and AWS is essential.', 4, 5, 'RECRUITMENT', 'PUBLISHED', NOW() - INTERVAL '12 hours', NOW() - INTERVAL '6 hours', NOW() + INTERVAL '15 days', 1, 20, 30, 'CloudTech', 'Ho Chi Minh City', '2200-3000 USD', '3-5 years', 'DevOps Engineer', '9AM-6PM', '2024-12-15', 'LinkedIn: CloudTech Careers'),
(2, 'Data Scientist - DataCorp', 'Join our data science team to work on machine learning projects and data analysis. Strong background in Python, ML algorithms, and statistical analysis required.', 5, 6, 'RECRUITMENT', 'PUBLISHED', NOW() - INTERVAL '6 hours', NOW() - INTERVAL '3 hours', NOW() + INTERVAL '18 days', 1, 25, 40, 'DataCorp', 'Hanoi', '2500-3500 USD', '4-6 years', 'Senior Data Scientist', '9AM-6PM', '2024-12-18', 'Apply at: datacorp.vn/careers'),
(2, 'UI/UX Designer - DesignStudio', 'We are seeking a creative UI/UX Designer to design user interfaces for our web and mobile applications. Proficiency in Figma, Adobe Creative Suite, and user research is required.', 6, NULL, 'RECRUITMENT', 'PENDING', NOW() - INTERVAL '2 hours', NULL, NOW() + INTERVAL '10 days', NULL, 0, 0, 'DesignStudio', 'Ho Chi Minh City', '1200-1800 USD', '2-4 years', 'UI/UX Designer', '9AM-6PM', '2024-12-10', 'Portfolio to: design@designstudio.vn'),
(2, 'Business Analyst - FinanceTech', 'Looking for a Business Analyst to analyze business requirements and work with development teams. Experience in financial services and agile methodologies preferred.', 2, NULL, 'RECRUITMENT', 'APPROVED', NOW() - INTERVAL '1 hour', NULL, NOW() + INTERVAL '12 days', 1, 5, 8, 'FinanceTech', 'Ho Chi Minh City', '1500-2000 USD', '2-3 years', 'Business Analyst', '8AM-5PM', '2024-12-12', 'Email: ba@financetech.vn');

-- Success message
SELECT 'News database sample data inserted successfully!' as message;
